version: "3.2"
services:
  movies:
    build:
      context: .
      dockerfile: ./movies/Dockerfile
    ports:
      - published: ${APP_PORT:-4000}
        target: 4000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      OMDB_KEY: ${OMDB_KEY}
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}