# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: run authorization app
        run: docker-compose run -e JWT_SECRET=secret --service-ports auth
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
        shell: bash
        working-directory: ./movies
      - run: npm test
        shell: bash
        working-directory: ./movies
        
