# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./movies
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: run authorization app
        uses: isbang/compose-action@v0.2.0
        with: 
          compose-file: ../docker-compose.yml
          run: docker-compose run -e JWT_SECRET=secret --service-ports auth
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
